
// const typeCachesKey = t
const cacheKeys = {
  IS_LOGGED: 'IS_LOGGED',
  // loading App
  LOADING_APP: 'LOADING_APP',
  DEMO_LIST: 'DEMO_LIST',
  DEMO_LIST_USER: 'DEMO_LIST_USER',
  USER_INFO: 'USER_INFO',
  SEARCH_HOME: 'SEARCH_HOME',
  SEARCH_USER_GROUP: 'SEARCH_USER_GROUP',
  CONTROL_SIDE_BAR: 'CONTROL_SIDE_BAR',
}

export default cacheKeys